version: '3.8'

services:
  # Aplicación principal - construir localmente
  app:
    build:
      context: ..
      dockerfile: DevOps/Dockerfile
    container_name: weather-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3001}
      - HOST=${HOST:-0.0.0.0}
      - DB_PATH=${DB_PATH:-./data/weather.db}
      - DB_BACKUP_PATH=${DB_BACKUP_PATH:-./backups}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - WEATHER_STATIONS=${WEATHER_STATIONS}
      - STATION_POLLING_INTERVAL=${STATION_POLLING_INTERVAL:-30000}
      - STATION_REQUEST_TIMEOUT=${STATION_REQUEST_TIMEOUT:-5000}
      - UDP_ENABLED=${UDP_ENABLED:-false}
      - UDP_PORT=${UDP_PORT:-22222}
      - UDP_HOST=${UDP_HOST:-0.0.0.0}
      - UDP_BROADCAST_INTERVAL=${UDP_BROADCAST_INTERVAL:-60000}
      - WS_PATH=${WS_PATH:-/ws}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - BACKUP_ENABLED=${BACKUP_ENABLED:-true}
      - BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS:-6}
      - ALERT_CHECK_INTERVAL=${ALERT_CHECK_INTERVAL:-60000}
      - DATA_COLLECTION_INTERVAL=${DATA_COLLECTION_INTERVAL:-60000}
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
      - app_backups:/app/backups
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: weather-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/simple.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - app_logs:/var/log/nginx
    networks:
      - app_network
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis para cache
  redis:
    image: redis:7-alpine
    container_name: weather-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - app_redis:/data
    networks:
      - app_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus para monitoreo
  prometheus:
    image: prom/prometheus:latest
    container_name: weather-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - app_prometheus:/prometheus
    networks:
      - app_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

volumes:
  app_data:
    driver: local
  app_logs:
    driver: local
  app_backups:
    driver: local
  app_redis:
    driver: local
  app_prometheus:
    driver: local

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
